name: Language Request
description: Request adding a new language.
title: "i18n(new): request i18n for [fill language here]"
labels: ["@i18n", "new language"]

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill this out!

        Fill this template only when:
        
        - The language doesn't exist in the language switcher.
        - And it also doesn't appear on [the project's translation page on Crowdin](https://crowdin.com/project/osu-collab-tools).
  - type: input
    id: lang
    attributes:
      label: The required language
      placeholder: "Example: Japanese"
    validations:
      required: true
  - type: dropdown
    id: native-lang
    attributes:
      label: Are you the native speaker of the requested language?
      options:
        - "Yes, and I would like to translate the project by myself."
        - "No, but I am able to translate the project into this language."
        - "No, I just want to see the project in the specified language."
    validations:
      required: true
  - type: checkboxes
    id: verify
    attributes:
      label: Finally, please check the following items twice.
      options:
        - "The requested language isn't included in the project's language list."
        - "I am unable to find the language on the project's language page on Crowdin."
    validations:
      required: true
